version: "3.7"
services:
  evolution_v2:
    image: evoapicloud/evolution-api:v2.3.0
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - network_swarm_public
    environment:
      - SERVER_URL=https://evo.labdigital.com.br
      - QRCODE_LIMIT=30
      - LANGUAGE=pt-BR
      - AUTHENTICATION_API_KEY=sua-key-gerada
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:SENHA@postgres:5432/evolution
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/1
      - CACHE_REDIS_PREFIX_KEY=evolution_v2
      - CACHE_REDIS_TTL=604800
      - CACHE_REDIS_SAVE_INSTANCES=true
      - OPENAI_ENABLED=true
      - DIFY_ENABLED=true
      - FLOWISE_ENABLED=true
      - N8N_ENABLED=true
      - EVOAI_ENABLED=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.evolution_v2.rule=Host(`evo.labdigital.digital`)
        - traefik.http.routers.evolution_v2.entrypoints=websecure
        - traefik.http.routers.evolution_v2.tls.certresolver=letsencryptresolver
        - traefik.http.routers.evolution_v2.service=evolution_v2
        - traefik.http.services.evolution_v2.loadbalancer.server.port=8080
        - traefik.http.services.evolution_v2.loadbalancer.passHostHeader=true
volumes:
  evolution_instances:
    external: true
    name: evolution_v2_data
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
